'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

penul = 0
ulti = 0
atual = 1
soma = 0

while atual < 4000000:
    if(atual%2 == 0):
        if(atual < 4000000):
            soma+=atual
    penul = ulti
    ulti = atual
    atual = ulti+penul

print('soma', soma)